import styled from "styled-components";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import ThemeProvider from "@/providers/theme.provider";
import { Roboto } from "next/font/google";

const roboto = Roboto({ subsets: ["latin"], weight: ["100", "400", "900"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={roboto.className}>{children}</body>
      </StyledComponentsRegistry>
    </html>
  );
}
